// Shared domain types. Imported as `import type { ... } from '@shared/types'`.

export type FontSize = "normal" | "large" | "xlarge"
export type PanelPosition = "left" | "right"
export type Theme = "light" | "dark"
export type ThemeColor = "red" | "blue" | "green"
export type ShortcutSize = "small" | "medium" | "large" | "xl" | "xl2"
export type ActivityType = "visit" | "search" | "save"

export interface SecurityConfig {
  blockDownloads: boolean
  blockAds: boolean
  /** Host names, e.g. ["onet.pl", "youtube.com"]. */
  blacklist: string[]
  /** Block sites on the bundled + periodically-refreshed malware/phishing domain list. */
  blockKnownMalware: boolean
}

export interface UIConfig {
  showHistory: boolean
  showBrowserSettings: boolean
}

/** Per-button admin config for the side panel. */
export interface PanelButtonConfig {
  label: string
  visible: boolean
}

export interface Config {
  caregiverName: string
  seniorName: string
  panelPosition: PanelPosition
  defaultFontSize: FontSize
  security: SecurityConfig
  ui: UIConfig
  /** Ordered list of panel button IDs. */
  panelButtonOrder: string[]
  /** Per-button overrides keyed by button ID. */
  panelButtons: Record<string, PanelButtonConfig>
  /** Set to true after caregiver completes (or skips) the setup wizard. */
  onboardingDone: boolean
  /** Set to true after the side-panel intro wizard is dismissed. */
  panelWizardDone: boolean
  /** PBKDF2-SHA256 hash of the caregiver's PIN — the raw PIN is never stored (see shared/pin.ts). */
  pinHash: string
  /** Random hex salt used to derive pinHash. */
  pinSalt: string
  /** Global display size applied to every shortcut tile. */
  shortcutSize: ShortcutSize
  /** When false the ☰ Panel button is hidden on all pages (caregiver toggle). */
  panelEnabled: boolean
  /** Light vs dark brightness selected by the user. */
  theme: Theme
  /** Accent colour palette selected by the user. */
  themeColor: ThemeColor
}

export interface Shortcut {
  /** UUID generated by crypto.randomUUID(). */
  id: string
  /** Caregiver-configurable display label. */
  label: string
  url: string
  /** Favicon URL or base64 data URI; absent → letter avatar. */
  iconUrl?: string
  /** Sort order in the grid. */
  position: number
  size: ShortcutSize
}

export interface SavedLink {
  id: string
  url: string
  title: string
  /** ISO 8601 timestamp. */
  savedAt: string
}

export interface ActivityLogEntry {
  url: string
  title: string
  /** ISO 8601 timestamp. */
  visitedAt: string
  type: ActivityType
}

/** Cached, periodically-refreshed malware/phishing domain list (see background/malwareBlocklist.ts). */
export interface MalwareList {
  domains: string[]
  /** ISO 8601 — null until the first successful remote refresh. */
  updatedAt: string | null
}

export interface SessionState {
  currentFontSize: FontSize | null
  previousFontSize: FontSize | null
  adminModeActive: boolean
}
