-- Base schema for the `licenses` table (audit finding #5/#7).
--
-- The original table was created manually in the Supabase dashboard and was
-- never committed, so the schema wasn't reproducible or reviewable. This
-- migration reconstructs it from what the edge functions actually read/write
-- (register-license, validate-license, lemon-squeezy-webhook).
--
-- It is fully idempotent: `if not exists` everywhere, so it is a safe no-op
-- against the existing production database and only does real work on a fresh
-- deploy (e.g. `supabase db reset`). The later 20260518 migration adds
-- install_id; 20260611 enables RLS + the rate limiter.
--
-- IMPORTANT (finding #1): license_key defaults to gen_random_uuid() — a
-- 122-bit random v4 UUID. This is what makes validate-license safe against
-- key enumeration. If your production column differs, align it.

create table if not exists public.licenses (
  id                      bigint generated by default as identity primary key,
  -- Secret, unguessable handle the extension stores and validates against.
  license_key             uuid        not null default gen_random_uuid() unique,
  -- Caregiver email — natural key for upserts (webhook onConflict: "email").
  email                   text        not null unique,
  -- trial | active | grace | expired
  status                  text        not null default 'trial',
  trial_ends_at           timestamptz,
  current_period_ends_at  timestamptz,
  -- Lemon Squeezy linkage, populated by the webhook.
  ls_subscription_id      text,
  ls_customer_id          text,
  created_at              timestamptz not null default now()
);

-- Lookups by license_key (validate-license) and email (register-license).
create unique index if not exists idx_licenses_license_key on public.licenses (license_key);
create unique index if not exists idx_licenses_email        on public.licenses (email);

-- Safe-by-default even if applied without the dedicated lockdown migration:
-- enable RLS with no public policy and strip the API roles' table access.
-- All legitimate access is via service-role edge functions, which bypass RLS.
alter table public.licenses enable row level security;
revoke all on public.licenses from anon;
revoke all on public.licenses from authenticated;
